### PR TITLE
Callback for config

### PR DESCRIPTION
**Pull request by mche**
# REASON

Declare plugin and its config in diffrent places

### CODE REVIEW

**Comment by jhthorsen** [comment]
I don't see which usecase this solves. Why can't you just do this instead:

    my $cb = sub {my $app = shift; { <provider> => {key => ..., secret => ...,} } };
    plugin "OAuth2" => $app->$cb;

I also don't understand why we need a new dependency.

**Comment by mche** [comment]
You have done for me discovery 

> $app->$cb

Where is there docs about?

Patch should be closed

**Comment by leejo** [comment]
> Where is there docs about?

This isn't mojo specific, it's just perl. `my $res = $object->$method( @args );`

**Comment by mche** [comment]
i understand $method as string but not coderef

**Comment by mche** [comment]
hehh

**Comment by jhthorsen** [comment]
@mche: There's a bunch of "perldoc" commands that can give you answers, but I like this:

http://shadow.cat/blog/matt-s-trout/madness-with-methods/

**Comment by mche** [comment]
thanks Jan & Lee

**Comment by mche** [comment]
My merge config
---

`my $providers = $self->providers;`
 ` { `
`    my ($name, $vals);`
`  @{ $providers->{$name} ||= {} }{ keys %$vals } = values %$vals`
`      while ($name, $vals) = each %$config;`
`  };`
`  $self->providers($providers);`

**Pull request closed without merging**
